In [38]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

In [3]:
import pandas as pd
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [13]:
# 实现归一化
scaler = MinMaxScaler() # 实例化
scaler = scaler.fit(data) # 生成min(x),max(x)
result = scaler.transform(data) # 导出结果

In [14]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [16]:
scaler.inverse_transform(result) #逆转结果

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [26]:
# #使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = MinMaxScaler(feature_range=[5,10]) #  实例化归一化到5~10之间
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [51]:
# 使用numpy来实现归一化
import numpy as np
X = np.array(data)
X

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [49]:
X_nor = (X - X.min(axis=0))/(X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [52]:
# 还原
X = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [ ]:
# 标准差 preprocessing.StandarScaler

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
scaler = StandardScaler() # 实例化
scaler.fit(data) # fit,本质用于生成均值和方差

StandardScaler(copy=True, with_mean=True, with_std=True)

In [56]:
# 对每一列向量表示一个特征，故对默认对列进行操作
scaler.mean_ # 查看均值的属性mean_
scaler.var_  # 查看方差的属性var_

array([-0.125,  9.   ])

In [60]:
# 导出结果
x_std = scaler.transform(data)
x_std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [63]:
# 结果均值为0，方差为1的标准正太分布
x_std.mean()
x_std.std()

1.0

In [64]:
scaler.inverse_transform(x_std) # 使用inverse_transform逆标准化

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])